### ISSUE TITLE
Uncaught TypeError: error is not a function

### ISSUE THREAD

**Issue by olumytee** [jhuenges/meteor-highstock#1]
Hello, I get this error when I try to use this package 
![highstock](https://cloud.githubusercontent.com/assets/463900/12932224/f938dfc4-cf81-11e5-90d7-57b0fb4efe09.JPG)
Update: It's okay now..It is caused by a conflict with maazalik:highcharts
Simply removing and readding maazalik:highcharts fixed the error

**Comment by olumytee** [comment]
Hi, seems the issue arises when I try to use it with maazalik:highcharts package, but I need both to work..please help

**Comment by jhuenges** [comment]
Okay :)
