### ISSUE TITLE
TypeError: error is not a function jhuenges_highstock.js:236:1

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [jhuenges/meteor-highstock#2]
hi got error in console.log, just added package

TypeError: error is not a function jhuenges_highstock.js:236:1

**Comment by jhuenges** [comment]
I need a little more than that.

**Comment by VeilleurTrytoFix** [comment]
fixed, simple download and add **/client/lib/highcharts.js** and **/client/lib/highstocks.js** to meteor project

**Comment by jhuenges** [comment]
This shouldnt be necessary
